### ISSUE TITLE
Timeout with upgrade_and_finalize

### ISSUE THREAD

**Issue by entone** [nerves-project/nerves_firmware#4]
Occasionally I receive timeout errors when calling Nerves.Firmware.upgrade_and_finalize(@stage_file)

Would be great to up the timeout beyond the default 5000

https://github.com/nerves-project/nerves_firmware/blob/master/lib/firmware.ex#L119

**Comment by ghitchens** [comment]
Absolutely agreed!  Amazing I haven't run into this yet.  I'm guessing you're on a platform with NAND flash or larger image that takes more than 5 seconds to write.   This should really have a much longer timeout, possibly minutes for some platforms.     Will address in my next pass.

**Comment by ghitchens** [comment]
Fixed by https://github.com/nerves-project/nerves_firmware/commit/e9c067c7bff4d04eef8d9e1e7bf3c25b388130d7
